general:
  # buildTool: Add the name of your build tool which fits your project. For example: maven, docker, npm
  productiveBranch: 'main'
  vaultPath: 'piper/PIPELINE-GROUP-70'
  vaultBasePath: 'piper/PIPELINE-GROUP-70'
  vaultPipelineName: 'mmt-devops-ui-cpi-delivery'
  vaultServerUrl: 'https://vault.tools.sap'
  vaultNamespace: 'ies/hyperspace/pipelines'
  nativeBuild: true
stages:
  Security:
    detectExecuteScan: true
  Release:
    sapDownloadArtifact: false
  Post:
    # Secret rotation handled by Hyperspace Portal, enabling it back might cause unintended behavior
    vaultRotateSecretId: false
steps:
  sapCallStagingService:
    url: 'https://staging.repositories.cloud.sap/stage/api'
    profile: 'group-70-default'
  sonarExecuteScan:
    serverUrl: 'https://sonar.tools.sap'
  sapCumulusUpload:
    pipelineId: 'd66a5815-572a-4f81-9236-41ee7681fa22'
  detectExecuteScan:
    serverUrl: https://sap.blackducksoftware.com
    groups: ['Delivery Orchestration for SAP Cloud Integration']
    scanners: []
    scanPaths: []
    detectTools: ['DETECTOR']
    npmDependencyTypesExcluded: ['DEV']
    scanProperties: [
        "--detect.accuracy.required=NONE",
        "--detect.project.version.distribution=SAAS",
        "--detect.timeout=6000",
        "--blackduck.trust.cert=true",
        "--min-scan-interval=0",
      ]
