name: OSS Compliance and PPMS
on:
  workflow_dispatch:
  push:
    branches:
    - "main"

jobs:
  oss-ppms:
    uses: "project-piper/piper-pipeline-github/.github/workflows/sap-oss-ppms-workflow.yml@v1"
    secrets: inherit
    permissions:
      contents: write
      id-token: write
